# CONFIGURACIÓN BÁSICA DE HUGO
baseURL                 = "https://www.pabloizaguerri.org"
title                   = "Pablo Izaguerri"
defaultContentLanguage  = "es"
defaultContentLanguageInSubdir = true

[languages.ca]
  locale = "ca"
  label = "Català"
  weight = 1
  copyright = "Pablo Izaguerri. Tots els drets reservats."
  [languages.ca.params]
    description = "Antropologia visual i fotografia documental"
  [[languages.ca.menu.main]]
    name = "Projectes"
    pageRef = "/proyectos"
    weight = 1
  [[languages.ca.menu.main]]
    name = "Blog"
    url = "/es/blog/" 
    weight = 2
  [[languages.ca.menu.main]]
    name = "Sobre jo"
    pageRef = "/about"
    weight = 3

[languages.es]
  locale = "es"
  label = "Español"
  weight = 2
  copyright = "Pablo Izaguerri. Todos los derechos reservados."
  [languages.es.params]
    description = "Antropología visual y fotografía documental"
  [[languages.es.menu.main]]
    name = "Proyectos"
    pageRef = "/proyectos"
    weight = 1
  [[languages.es.menu.main]]
    name = "Blog"
    pageRef = "/blog"
    weight = 2
  [[languages.es.menu.main]]
    name = "Sobre mí"
    pageRef = "/about"
    weight = 3

[languages.en]
  locale = "en"
  label = "English"
  weight = 3
  copyright = "Pablo Izaguerri. All rights reserved."
  [languages.en.params]
    description = "Visual anthropology and documentary photography"
  [[languages.en.menu.main]]
    name = "Projects"
    pageRef = "/proyectos"
    weight = 1
  [[languages.en.menu.main]]
    name = "Blog"
    url = "/es/blog/" 
    weight = 2
  [[languages.en.menu.main]]
    name = "About"
    pageRef = "/about"
    weight = 3

[build]
  publishResources = false

[imaging]
  quality = 82
  resampleFilter = "lanczos"
  formats = ["webp", "jpg"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      definitionList = true
      footnote       = true
      linkify        = true
      strikethrough  = true
      table          = true
      taskList       = true
      typographer    = true
      attribute      = true

[params]
  logo = "/images/profilepic.png"
  
  [params.author]
    name  = "Pablo Izaguerri"
    email = "infopizaguerri@pm.me"
  
  [params.assets]
    customCSS = ["css/custom.css"]
  
  [params.gallery]
    lightbox_download = false
  
  [params.socialIcons]
    email     = "mailto:infopizaguerri@pm.me"
    instagram = "https://www.instagram.com/pizaguerri/"
    mastodon  = "https://mastodon.social/@Pizzaguerri"
    youtube   = "http://www.youtube.com/@Pizzaguerri"
    github    = "https://github.com/Pizaguerri"

    [outputs]
      home = ["HTML", "RSS"]
      section = ["HTML", "RSS"]
      page = ["HTML"]