# CONFIGURACIÓN BÁSICA DE HUGO
baseURL                 = "https://www.pabloizaguerri.org"
title                   = "PABLO IZAGUERRI"
defaultContentLanguage = "ca"
defaultContentLanguageInSubdir = false

[[languages.ca.menu.main]]
    name = "ÍNDEX"
    pageRef = "/projects"
    weight = 1
  [[languages.ca.menu.main]]
    name = "ABOUT"
    pageRef = "/about"
    weight = 2

[[languages.es.menu.main]]
    name = "ÍNDICE"
    pageRef = "/projects"
    weight = 1
    [[languages.es.menu.main]]
    name = "ABOUT"
    pageRef = "/about"
    weight = 2

[[languages.en.menu.main]]
    name = "INDEX"
    pageRef = "/projects"
    weight = 1
    [[languages.en.menu.main]]
    name = "ABOUT"
    pageRef = "/about"
    weight = 2

[build]
  publishResources = false

[imaging]
  quality = 82
  resampleFilter = "lanczos"
  formats = ["webp", "jpg"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      definitionList = true
      footnote       = true
      linkify        = true
      strikethrough  = true
      table          = true
      taskList       = true
      typographer    = true
      attribute      = true

[params]
  logo = "/images/profilepic.png"
  
  [params.author]
    name  = "Pablo Izaguerri"
    email = "infopizaguerri@pm.me"
  
  [params.assets]
    customCSS = ["css/custom.css"]
  
  [params.gallery]
    lightbox_download = false
  
  [params.socialIcons]
    email     = "mailto:infopizaguerri@pm.me"
    instagram = "https://www.instagram.com/pizaguerri/"
    mastodon  = "https://mastodon.social/@Pizzaguerri"
    youtube   = "http://www.youtube.com/@Pizzaguerri"
    github    = "https://github.com/Pizaguerri"
    codeberg  = "https://codeberg.org/Pizaguerri"

    [outputs]
      home = ["HTML", "RSS"]
      section = ["HTML", "RSS"]
      page = ["HTML"]